---
# tasks file for haproxy
- name: install haproxy
  package:
    name: haproxy
    state: latest

- name: configure haproxy service
  service: 
    name: haproxy
    state: started
    enabled: true

- template: 
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart_haproxy
